[package]
name = "query-engine-metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
metrics.workspace = true
metrics-util = "0.17.0"
metrics-exporter-prometheus = "0.10.0"
once_cell = "1.3"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-futures = "0.2"
tracing-subscriber = "0.3.11"
parking_lot = "0.12"

[dev-dependencies]
expect-test = "1"
tokio.workspace = true
