[package]
edition = "2021"
name = "sql-schema-connector-wasm"
version = "0.1.0"

[dependencies]
psl.workspace = true
quaint = { workspace = true }
serde.workspace = true
indoc.workspace = true
uuid.workspace = true
indexmap.workspace = true

prisma-value = { path = "../../../libs/prisma-value" }
sql-ddl = { path = "../../../libs/sql-ddl" }

chrono.workspace = true
connection-string.workspace = true
enumflags2.workspace = true
once_cell = "1.3"
regex.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
url.workspace = true
either = "1.6"
sqlformat = "0.2.1"
sqlparser = "0.32.0"
versions = "6.1.0"

[dev-dependencies]
expect-test = "1"
