[package]
edition.workspace = true
name = "psl-core"
version = "0.1.0"

[features]
postgresql = []
sqlite = []
mysql = []
cockroachdb = ["postgresql"]
mssql = []
mongodb = []
std = ["dep:connection-string"]

[dependencies]
diagnostics.workspace = true
parser-database.workspace = true
prisma-value.workspace = true
schema-ast.workspace = true

bigdecimal.workspace = true
chrono.workspace = true
connection-string = { workspace = true, optional = true }
itertools.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
enumflags2.workspace = true
indoc.workspace = true
either.workspace = true
hex.workspace = true
hashbrown = { workspace = true, features = ["serde"] }
lazy-race.workspace = true

# For the connector API.
lsp-types.workspace = true
url.workspace = true
cfg-if.workspace = true
